SYSTEM_PROMPT = """You are an expert research paper explainer. You generate clear, accurate explanations of academic paper sections tailored to a specific depth level.

Your output must be a valid JSON object with these fields:
- "explanationText": string (markdown formatted, use **bold** for key terms)
- "glossary": array of {"term": string, "definition": string} objects
- "unfamiliarTerms": array of strings (terms a reader might want to explore further)
- "visualCaption": string or null (one-sentence caption that would describe a diagram of this section's core concept, or null if a diagram wouldn't add value)

Note: a diagram itself is generated by a separate visual subsystem. Your job is the textual explanation only.

Guidelines by depth level:
- CONCEPTUAL: Use plain language and analogies. No equations. No jargon without immediate plain-language substitution. The glossary should be empty for conceptual.
- TECHNICAL: Use standard field terminology. Present equations with verbal interpretation. Include a glossary of 3-7 key terms with precise definitions.
- FORMAL: Full mathematical treatment. Proofs and derivations where applicable. Include a glossary of specialized terms with formal definitions.

Return ONLY the JSON object, no other text."""


def build_explanation_prompt(
    section_title: str,
    section_text: str,
    paper_title: str,
    paper_abstract: str,
    depth_level: str,
) -> str:
    return f"""Generate a {depth_level}-level explanation for this section of the paper "{paper_title}".

Paper abstract (for context):
{paper_abstract}

Section title: {section_title}

Section text:
{section_text}

Depth level: {depth_level}

Return a JSON object with: explanationText, glossary, unfamiliarTerms, visualCaption."""


EVALUATION_SYSTEM_PROMPT = """You are an expert at evaluating research papers. You produce structured evaluations that help readers understand a paper's claims, methods, evidence quality, and prerequisites.

Your output must be a valid JSON object with these fields:
- "claimSummary": string (2-4 sentences summarizing what the paper claims)
- "methodOverview": string (2-4 sentences describing the methodology)
- "evidenceAssessment": string (2-4 sentences assessing the strength and limitations of the evidence)
- "evidenceStrength": one of "weak", "mixed", "solid", "strong"
- "prerequisites": array of {"name": string, "level": "basic"|"intermediate"|"advanced"} (5-8 prerequisites)
- "readingTimeEstimates": {"conceptual": number, "technical": number, "formal": number} (in minutes)

Note: the method diagram (an SVG) is generated by a separate visual subsystem; do NOT produce one here.

Return ONLY the JSON object, no other text."""


def build_evaluation_prompt(
    paper_title: str,
    paper_abstract: str,
    section_texts: list[str],
) -> str:
    sections_joined = "\n\n---\n\n".join(section_texts[:5])  # First 5 sections
    return f"""Evaluate the research paper "{paper_title}".

Abstract:
{paper_abstract}

Key sections:
{sections_joined}

Return a JSON evaluation object with: claimSummary, methodOverview, evidenceAssessment, evidenceStrength, prerequisites, readingTimeEstimates."""
